\import Combinatorics.Binom
\import Function
\import Logic
\import Paths.Meta
\import Set
\import Set.Fin

\func \infix 5 SubSets' (n k : Nat) : \Set => \Sigma (x : Fin k -> Fin n) (p : isInj x)
\func char {n k : Nat} {x y : n SubSets' k}(p-eq : \Pi(r : Fin k) -> x.1 r = y.1 r) : x = y => exts p-eq
\func mega_char     {n k : Nat} {x y : n SubSets' k}(p-eq :  x.1 = y.1) : x = y => {?}

\func inv_char {n k : Nat} {x y : n SubSets' k}(p-eq : x = y) : x.1 = y.1 => {?}

\func sameFunc {n k : Nat}(x y : Fin k -> Fin n) : (x = y) || Not (x = y) => {?}

--\func sameFunc' {n k : Nat}(x y : Fin k -> Fin n)
--  : (\Pi(r : Fin k) -> x r = y r) || Not (\Pi(r : Fin k) -> x r = y r)

\instance SubSets(n k : Nat) : FinSet \cowith
  | E => n SubSets' k
  | finCard => binom n k
  | decideEq x y => \case sameFunc x.1 y.1 \with {
    | byLeft a => yes (mega_char a)
    | byRight b => no (\lam z => b (inv_char z))
  }
  | finEq => {?}