\import Algebra.Field
\import Algebra.Group
\import Algebra.Group.Category
\import Algebra.Group.Representation.Category
\import Algebra.Group.Representation.MaschkeTheorem
\import Algebra.Group.Representation.Product
\import Algebra.Group.Representation.Representation
\import Algebra.Group.Representation.SumOverGroup
\import Algebra.Module
\import Algebra.Module.Category
\import Algebra.Module.LinearMap
\import Algebra.Ring
\import Category
\import Function
\import Logic
\import Logic.Meta
\import Paths
\import Paths.Meta

\class SubLRepres {R : Ring} {G : Group} (E : LRepres R G) (\classifying S : LRepres R G ){
  | in : InterwiningMap S E
  | in-mono : isInj in

  \func isTrivial => isZeroMod S || isSurj in


  \func directSummand => ∃(K : SubLRepres E)(Iso (ProductLRepres.coprod-map in K.in))

  \func \infix 7 ap (g : G)(s : S) : S => (LinRepres.** {S}) g s


  -- TODO : rewrite it with extension
  \func recast : SubLModule_external E \cowith
    | S => S
    | in => in
    | in-mono => in-mono
}

\func KernelSubLRepres{R : Ring}{G : Group}{A B : LRepres R G}(f : InterwiningMap A B) : SubLRepres A \cowith
  | S => KerLRepres f
  | in => KerLRepresHom f
  | in-mono {a a' : KerLRepres f} => \lam (p : KerLRepresHom f a = KerLRepresHom f a') => exts p

\func ImageSubLRepres {R : Ring} {G : Group} {A B : LRepres R G} (f : InterwiningMap A B) : SubLRepres B \cowith
  | S => ImageLRepres {R} {G} {A} {B} f
  | in => ImageLRepresRightHom f
  | in-mono {a a' : ImageLRepres f} => \lam (p : ImageLRepresRightHom f a = ImageLRepresRightHom f a') => ext p
